export const quotes = [
  "Narrow your world to widen your output.",
  "Distraction isn't the enemy—lack of intent is.",
  "What you choose to ignore shapes your future.",
  "Scatterfocus isn't lazy, it's creative fuel.",
  "Attention is a muscle, train it daily.",
  "Let your mind drift, then reel it back sharp.",
  "True reward comes right after you finish.",
  "Journaling turns tangled thoughts into power.",
  "Ten focused minutes top five hours drifting.",
  "Attention is currency—spend it wisely.",
  "Exhale noise, inhale what matters.",
  "Progress always wins over perfect.",
  "Clock's running—make every tick worth it.",
  "Don't fight wandering, just steer it.",
  "Flow state: quiet mind, loud results.",
  "One deep task beats ten shallow ones.",
  "Focus isn't forced, it's invited.",
  "Rewards aren't gold, they're closure.",
  "Your next breakthrough hides in boredom.",
  "Clarity starts when clutter leaves.",
  "Mind like water—still, then ripple.",
  "Done is better than dreaming.",
  "Attention paid today, pays you back.",
  "Hyperfocus: laser on, world off.",
  "Scatter mode—let ideas breathe.",
  "Log it, learn it, leave it behind.",
  "Streak isn't luck, it's discipline.",
  "Every pause sharpens your return.",
  "What you track, you tend to.",
  "Silence breeds your sharpest thoughts.",
  "Momentum starts with one click.",
  "Focus isn't loud, it's steady.",
  "Reward yourself with proof.",
  "Mind maps beat mind mess.",
  "Time bends when you're in.",
  "Write it, right it, run with it.",
  "Attention surplus beats time surplus.",
  "One hour pure—worth a whole day.",
  "Let go of tabs, hold one truth.",
  "Insights wait in the quiet.",
  "Clock doesn't lie, habits do.",
  "Finish small, feel giant.",
  "Focus is freedom in disguise.",
  "Scatter to gather later.",
  "Log mood, map mood.",
  "Every tick counts—own it.",
  "Badge up, doubt down.",
  "Flow isn't luck, it's ritual.",
  "Write the mess, watch it clear.",
  "Attention: your silent superpower.",
  "Streak alive, spirit alive.",
  "Rewards stack like muscle.",
  "One deep breath, one deep dive.",
  "Mind drift—then direction.",
  "Progress rings louder than goals.",
  "Focus sharp, day softens.",
  "Unlock flow, unblock life.",
  "Journal: today's seed, tomorrow's tree.",
  "Clock spins—ride it.",
  "Attention paid, peace gained.",
  "Scatter sparks, focus strikes.",
  "Done fuels the next.",
  "Mind like lens—zoom in.",
];
